[tasks.validate]
description = "Validate resume.json"
run = "scripts/validate.sh"

[tasks.clean]
description = "Clean generated files"
run = "scripts/clean.sh"

[tasks.check]
description = "Static check files"
run = "scripts/check.sh"

[tasks.fix]
description = "Static fix files"
run = "scripts/fix.sh"
